services:
  ner-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ner-finetuning-api
    ports:
      - "8347:8347"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # GPU support (uncomment if using NVIDIA GPU)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8347/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

